### ISSUE TITLE
ENH: Fetch NCBI Taxonomy Data (input to `build_custom_diamond_db` action)

### ISSUE THREAD

**Issue by Sann5** [bokulich-lab/q2-moshpit#107]
### Context
The `build_custom_diamond_db` action can optionally take a `ReferenceDB[NCBITaxonomy]` artifact, with which the resulting Diamond database contains taxonomy features. There is a need to create an action that produces this `ReferenceDB[NCBITaxonomy]` artifact by fetching the appropriate data from the internet.

Something like...
```bash
qiime moshpit fetch-ncbi-taxonomy-db ...
```

### Important Considerations
There are two links from where the data comes from. One can find out the time and date of the last modification to the file on the server by calling `wget -S --spider <somewhere_in_the_internet>`. It might be important to include this data in the artifact since the version might influence the results. 

```[tasklist]
### Tasks
- [ ] https://github.com/bokulich-lab/q2-moshpit/issues/108
- [ ] https://github.com/bokulich-lab/q2-moshpit/issues/115
- [ ] bokulich-lab/q2-types-genomics/issues/72
- [ ] https://github.com/bokulich-lab/q2-moshpit/issues/102
```
