### ISSUE TITLE
MAINT: Add citation to actions that use eggNOG and/or Diamond

### ISSUE THREAD

**Issue by Sann5** [bokulich-lab/q2-moshpit#119]
Some eggNOG/Diamond action-registrations are missing the citations field in the `plugin_setup.py`.
```[tasklist]
### Tasks
- [ ] https://github.com/bokulich-lab/q2-moshpit/issues/115
- [ ] https://github.com/bokulich-lab/q2-moshpit/issues/108
- [ ] https://github.com/bokulich-lab/q2-moshpit/issues/107
- [ ] bokulich-lab/q2-types-genomics#72
```
